name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: .

      - name: Build Docusaurus site
        run: npm run build
        working-directory: .

      - name: Checkout central docs repo
        uses: actions/checkout@v4
        with:
          repository: panualaluusua/docs
          token: ${{ secrets.DOCS_PUSH_TOKEN }}
          path: central-docs

      - name: Copy built docs to central repo
        run: |
          rm -rf central-docs/docs/${{ github.event.repository.name }}
          mkdir -p central-docs/docs/${{ github.event.repository.name }}
          cp -r build/* central-docs/docs/${{ github.event.repository.name }}/

      - name: Commit and push docs to central repo
        run: |
          cd central-docs
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update docs for ${{ github.event.repository.name }} [skip ci]" || echo "No changes to commit"
          git push
